<%@ Page Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeFile="AdminPanel.aspx.cs" Inherits="AdminPanel" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <title>Админ панель</title>
    <meta name="description" content=" Сторінка, яка використовує майстер сторінок" />
    <meta charset="windows-1251" />

</asp:Content>

<asp:Content ID="content" ContentPlaceHolderID="contentPlaceHolder" runat="server">

    <div class="contentTitle">Панель администратора</div>
    <div>
        <br />
        <asp:Label ID="Label1" runat="server" Text="Незарегистрированые пользователи"></asp:Label>
        <br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating">
        </asp:GridView>

        <table>
            <tr>
                <td>
                    <asp:Label ID="Label2" runat="server" Text="Редактирование рубрик"></asp:Label></td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="Label4" runat="server" Text="Название "></asp:Label></td>
                <td>
                    <asp:TextBox ID="CatName" runat="server"></asp:TextBox></td>
            </tr>
            <tr>
                <td>
                    <asp:Label ID="Label5" runat="server" Text="Родительская рубрика"></asp:Label></td>
                <td>
                    <asp:DropDownList ID="ParentCatList" runat="server" OnSelect OnSelectedIndexChanged="ParentCatList_SelectedIndexChanged">
                    </asp:DropDownList></td>
            </tr>
            <tr>
                <td>
                    <asp:Button ID="AddCateg" runat="server" Text="Добавить" OnClick="AddCateg_Click" /></td>
            </tr>
        </table>


        <asp:GridView ID="Categories" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="Categories_RowDeleting">
        </asp:GridView>
        <br />
        <asp:Label ID="Label3" runat="server" Text="Добавление книги"></asp:Label>
        <br />
        <br />
        <br />
        <asp:GridView ID="GridView3" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        </asp:GridView>
        <br />

    </div>


</asp:Content>
